### PR TITLE
use vite library mode instead of tsup

### PR DESCRIPTION
**Pull request by wtchnm**

### CODE REVIEW

**Comment by wesbos** [comment]
is this just for builds?

**Comment by wtchnm** [comment]
do you ask if we can use Vite for dev too?

**Comment by wtchnm** [comment]
i added a dev script :)

**Comment by wesbos** [comment]
Sorry I thought this was asking to use lib mode for the purpose of this plugin, not for builds. I think this is great, will try it shortly

**Comment by wtchnm** [comment]
sorry for the the confusion, PR title fixed

**Comment by wesbos** [comment]
sorry for the delay - thanks for this!

**Pull request merged**
